//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OGLEvent.rc
//
#define ID_POSE_ADJ                     2
#define ID_PROJ_MAPPING                 3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OGLEVETYPE                  129
#define IDD_FORM_COMMAND                130
#define IDC_CURSOR_ROTATION             131
#define IDD_VIEW_MAPPING                132
#define IDM_MEMORY_INSUFFICIENT         133
#define IDD_txt_map                     133
#define IDM_READFILE_ERROR              134
#define IDD_OPERATION                   134
#define IDM_FILEFORMAT_ERROR            135
#define IDC_CURSOR1                     135
#define IDB_BITMAP1                     138
#define IDD_DATA_INPUT                  139
#define IDB_BITMAP_0                    140
#define IDB_BITMAP_1                    142
#define IDD_AREA_CMPT                   145
#define IDD_VLMN_CMPT                   146
#define IDC_CHECK_ANTIALIAS             1000
#define IDC_CHECK_SMOOTH                1001
#define IDC_CHECK_LIGHTING              1002
#define IDC_RADIO_MODEL_VERTEX          1003
#define IDC_RADIO_MODEL0                1003
#define IDC_RADIO_MODEL_WIREFRAME       1004
#define IDC_RADIO_MODEL1                1004
#define IDC_RADIO_MODEL_FACE            1005
#define IDC_RADIO_MODEL2                1005
#define IDC_CHECK_VROTATION             1006
#define IDC_CHECK_LINK_SCALE            1007
#define IDC_SLIDERSCALEX                1008
#define IDC_SLIDERSCALEY                1009
#define IDC_SLIDERSCALEZ                1010
#define IDC_FRAME_COLOR_LIGHT_SPECULAR  1011
#define IDC_FRAME_COLOR_LIGHT_DIFFUSE   1012
#define IDC_FRAME_COLOR_LIGHT_AMBIENT   1013
#define IDC_FRAME_COLOR_BACK            1014
#define IDC_FRAME_COLOR_FACE1           1015
#define IDC_FRAME_COLOR_FACE2           1016
#define IDC_CHECK_AXIS                  1016
#define IDC_FACE1                       1017
#define IDC_FACE2                       1018
#define IDC_CHECK_TXTMAP                1018
#define IDC_CHECK_Rot_X                 1019
#define IDC_CHECK_Rot_Y                 1020
#define IDC_H                           1020
#define IDC_CHECK_Rot_Z                 1021
#define IDC_HEIGHT                      1021
#define IDC_RADIO_PROJ                  1022
#define IDC_WIDTH                       1022
#define IDC_RADIO_ORTH                  1023
#define IDC_W                           1023
#define IDC_RADIO_PHOTO                 1024
#define IDC_RADIO_COLOR                 1025
#define IDC_CHECK_MESHPROJ              1026
#define IDC_READ_MODEL                  1027
#define IDC_READ_IMAGE                  1028
#define IDC_PT_LOC_1                    1029
#define IDC_BUTTON1                     1029
#define IDC_BUTTON_INVISIBLE            1029
#define IDC_POSE_ADJ                    1030
#define IDC_MTX_CPT                     1030
#define IDC_PROJ_MAP                    1031
#define IDC_TXT_BLEND                   1032
#define IDC_PRMT_OPT                    1033
#define IDC_PT_LOC_2                    1034
#define IDC_TXT_BLEND2                  1035
#define IDC_INVISIBLE                   1036
#define IDC_ITERATIVE                   1037
#define IDC_NEXTVIEW                    1038
#define IDC_SAVEIMAGE                   1039
#define IDC_M13                         1040
#define IDC_M14                         1041
#define IDC_AREA                        1042
#define IDC_VALUE                       1044
#define IDC_AREA_VALUE                  1044
#define IDC_VLMN                        1045
#define IDC_VLMN_VALUE                  1046
#define IDC_M21                         1051
#define IDC_M23                         1052
#define IDC_M24                         1053
#define IDC_M22                         1054
#define IDC_M31                         1055
#define IDC_M33                         1056
#define IDC_M34                         1057
#define IDC_M32                         1058
#define IDC_M12                         1059
#define IDC_M11                         1060
#define IDC_ERROR_SUM                   1061
#define IDC_PXL_COMP                    1062
#define IDC_MAP                         1063
#define ID_READIN                       32771
#define ID_READIN1                      32771
#define ID_MUNUAL                       32772
#define ID_AUTO                         32773
#define ID_INIT_ANGLE                   32774
#define ID_FILEOPEN                     32775
#define ID_READIN2                      32776
#define ID_FP_LOCALIZATION              32777
#define ID_VIEW_TRANS                   32778
#define ID_TXT_MAPPING                  32779
#define ID_FRONT_VIEW                   32780
#define ID_RIGHT_VIEW                   32781
#define ID_LEFT_VIEW                    32782
#define ID_SAVE                         32783
#define ID_SAVE_DATA                    32784
#define ID_DATA_ALALYSIS                32785
#define ID_READ_BKGD                    32786
#define ID_READ_FGD                     32787
#define ID_MENUITEM32788                32788
#define ID_IMG_DIFF                     32788
#define ID_AREA_CMPT                    32789
#define ID_VLMN_CMPT                    32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
